### ISSUE TITLE
Suggested materials

### ISSUE THREAD

**Issue by benjaminpope** [astroteaching/astroteaching.github.io#1]
Below are the contents of my Evernote document with astro teaching related materials - there may be some overlap with yours and some of it is general physics/ed research/specific courses, but some might be helpful:

Astronomy Education Journal:
- https://astroedjournal.org/index.php/ijae/issue/view/1

Stellar Physics Resources:
- Nikolina (Niko) Šarčević
- https://drive.google.com/drive/folders/1XApdgc0qiLuUoI6X7o_8GHFhcUp5PtF7?usp=sharing

Astro Problem Sheets
- Nikolina (Niko) Šarčević
- https://github.com/nikosarcevic/PhysicsProblemSets

Open Astrophysics Bookshelf
- https://open-astrophysics-bookshelf.github.io/

Effects of Popular Science Writing Instruction on General Education Student Attitudes Towards Science: A Case Study in Astronomy
- Lewis et al
- https://arxiv.org/abs/2209.02852
- https://astroedjournal.org/index.php/ijae/article/view/49 

Dust scattering rings in GRB
- https://twitter.com/jonastrox/status/1579816995729833984

Daniel Green notes
- https://drgreen.physics.ucsd.edu/teaching/
- 2018-22 – Physics 105a: Mathematical and Computational Physics
- 2019-21- Physics 161: Black Holes
- 2022- Physics 39: Computational Physics with Python 

Astrobites Lesson Plans:
- https://astrobites.org/educational-resources/edu2022/

Ungrading: 
- https://pressbooks.howardcc.edu/ungrading/chapter/ungrading-in-a-general-education-science-course/

Harvard Natural Sciences Lecture Demonstrations
- https://sciencedemonstrations.fas.harvard.edu/catalog 

Annual Reviews:
- https://www.annualreviews.org/doi/abs/10.1146/annurev-astro-032620-021943

**Comment by avapolzin** [comment]
Thank you; added! These are great suggestions :)
