### ISSUE TITLE
Repository of online astrophysics talks/seminars/lectures

### ISSUE THREAD

**Issue by ddhendriks** [astroteaching/astroteaching.github.io#3]
I have made a website that presents a collection of online available astrophysics talks:

[https://dhendriks.gitlab.io/astrotalks/](https://dhendriks.gitlab.io/astrotalks/)

A link to this website may be fitting in the misc. section.

PS: I have not updated the website for a bit because i'm working on a new version. Will update soon.

**Comment by avapolzin** [comment]
Ah, this is great. I've added it to the site; thank you!!
